[package]
name = "core_rust"
version = "2026.8.0"
edition = "2024"

[lib]
name = "_core_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module", "abi3-py39"] }
ndarray = { version = "0.16.1", features = ["rayon"]}
numpy = { version = "0.27" }
sasktran2-rs = { path = "../sasktran2-rs" }
sasktran2-core = { path = "../sasktran2-core" }
rebasis = { path = "../rebasis" }
rayon = "*"
anyhow = "*"
nalgebra = "0.34.1"

[features]
nightly = ["sasktran2-rs/nightly"]
