version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

  commands:
    - |
      curl https://sh.rustup.rs -sSf | sh -s -- -y && . "$HOME/.cargo/env"
      curl -fsSL https://pixi.sh/install.sh | bash
      pixi install -e default
      pixi r build
      pixi run -e default readthedocs

sphinx:
   configuration: docs/source/conf.py
