version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

  jobs:
    pre_build:
      - curl https://sh.rustup.rs -sSf | sh -s -- -y && . "$HOME/.cargo/env" && pip install .

sphinx:
   configuration: docs/sphinx/source/conf.py

conda:
  environment: conda/dev_env.yml
