version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"

  commands:
    - |
      curl https://sh.rustup.rs -sSf | sh -s -- -y && . "$HOME/.cargo/env"
      curl -fsSL https://pixi.sh/install.sh | bash
      /home/docs/.pixi/bin/pixi install -e default
      /home/docs/.pixi/bin/pixi r build
      /home/docs/.pixi/bin/pixi run -e default readthedocs

sphinx:
   configuration: docs/source/conf.py
