[package]
name = "sasktran2_bindings"
version = "0.1.0"
edition = "2024"
build = "build.rs"
links = "sasktran2"

[build-dependencies]
bindgen = "*"
cmake = "*"

[dependencies]
ndarray = "*"
anyhow = "*"
