{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set describe_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set describe_hash = environ.get('GIT_DESCRIBE_HASH', 'untagged') %}
{% set py_version = environ['CONDA_PY'] %}


package:
  name: sasktran2
  version: {{ version }}

source:
  git_url: ../

build:
  binary_relocation: true
  number: {{ describe_number }}
  string: {{ describe_hash }}
  script:
    - export CMAKE_ARGS=${CMAKE_ARGS};-DSKTRAN_BLAS_VENDOR=Generic
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - cmake >=3.5
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
  host:
    - python {{ python }}
    - eigen
    - libblas=*=*netlib
    - libcblas=*=*netlib
    - liblapack=*=*netlib
    - liblapacke=*=*netlib
    - libtmglib=*=*netlib
    - catch2
    - llvm-openmp # [mac]
    - zlib
    - pybind11
    - scikit-build-core
  run:
    - python {{ python }}
    - numpy
    - libblas=*=*netlib
    - libcblas=*=*netlib
    - liblapack=*=*netlib
    - liblapacke=*=*netlib
    - libtmglib=*=*netlib
    - llvm-openmp # [mac]

test:
  requires:
    - pytest
  imports:
    - sasktran2
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  home: http://www.example.com
  license: MIT
  summary: "Summary in here ..."