{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set describe_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set describe_hash = environ.get('GIT_DESCRIBE_HASH', 'untagged') %}
{% set py_version = environ['CONDA_PY'] %}

package:
  name: libsasktran2
  version: {{ version }}

source:
  git_url: ../ # this can be changed to git-url

build:
  number: {{ describe_number }}
  string: {{ describe_hash }}
  binary_relocation: true
  script:
    - cmake ${CMAKE_ARGS} -H. -Bbuild_conda -G "${CMAKE_GENERATOR}" -DCMAKE_INSTALL_PREFIX=${PREFIX} -DFORCE_BOOST_STATIC=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DSKTRAN_BLAS_VENDOR=Generic # [not win]
    - cmake ${CMAKE_ARGS}  -H. -Bbuild_conda -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" -DFORCE_BOOST_STATIC=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DSKTRAN_BLAS_VENDOR=Generic # [win]
    - cmake --build build_conda --config Release --target install

requirements:
  build:
    - cmake >=3.5
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
  host:
    - boost-cpp
    - libblas=*=*netlib
    - libcblas=*=*netlib
    - liblapack=*=*netlib
    - liblapacke=*=*netlib
    - libtmglib=*=*netlib
    - eigen
    - catch2
    - llvm-openmp # [mac]
    - zlib
  run:
    - boost-cpp
    - llvm-openmp # [mac]
    - zlib
    - libblas
    - libcblas
    - liblapack
    - liblapacke

about:
  home: http://www.example.com
  license: MIT
  summary: "Summary in here ..."