{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set describe_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set describe_hash = environ.get('GIT_DESCRIBE_HASH', 'untagged') %}
{% set py_version = environ['CONDA_PY'] %}
{% set cpu_count = environ['CPU_COUNT'] %}


package:
  name: sasktran2
  version: {{ version }}

source:
  git_url: ../

build:
  binary_relocation: true
  script_env:
    - CMAKE_BUILD_PARALLEL_LEVEL={{ cpu_count }}
    - DO_STREAM_TEMPLATES=ON # [not win]
  number: {{ describe_number }}
  string: py_{{ py_version }}_{{ describe_hash }}_{{ describe_number }}
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - cmake >=3.5
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }} # [not win]
  host:
    - python {{ python }}
    - eigen
    - libblas=*=*netlib
    - libcblas=*=*netlib
    - liblapack=*=*netlib
    - liblapacke=*=*netlib
    - libtmglib=*=*netlib
    - catch2
    - llvm-openmp # [osx]
    - zlib
    - pybind11>=2.10.2
    - spdlog
    - scikit-build-core
    - setuptools-scm
  run:
    - python {{ python }}
    - numpy
    - spdlog
    - netcdf4
    - fmt
    - appdirs
    - pyyaml
    - xarray
    - scipy
    - liblapacke
    - libblas

test:
  requires:
    - pytest
    - nomkl # [win]
  imports:
    - sasktran2
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  home: https://github.com/usask-arg/sasktran2
  license_file:
    - license.md
  summary: "The SASKTRAN radiative transfer model Version 2"
  doc_url: https://sasktran2.readthedocs.io/
