name: Benchmark

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

jobs:
  benchmark:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'run-benchmark') && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Linux
    runs-on: ubuntu-20.04
    env:
      ASV_DIR: "./asv_bench"
      CONDA_ENV_FILE: conda/dev_env.yml

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ${{env.CONDA_ENV_FILE}}
          create-args: >-
            asv


      - name: Run benchmarks
        shell: bash -l {0}
        id: benchmark
        env:
          OPENBLAS_NUM_THREADS: 1
          MKL_NUM_THREADS: 1
          OMP_NUM_THREADS: 1
          ASV_FACTOR: 1.05
          ASV_SKIP_SLOW: 1
        run: |
          set -x
          # ID this runner
          asv machine --yes
          echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
          echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"
          # Use mamba for env creation
          # export CONDA_EXE=$(which mamba)
          export CONDA_EXE=$(which conda)
          # Run benchmarks for current commit against base
          ASV_OPTIONS="--factor $ASV_FACTOR"
          asv run ${{ github.event.pull_request.base.sha }}^!
          asv run ${GITHUB_SHA}^!
          asv compare $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
              | tee benchmarks.log
        working-directory: ${{ env.ASV_DIR }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: asv-benchmark-results-${{ runner.os }}
          path: ${{ env.ASV_DIR }}/benchmarks.log

  save-pr-number:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'run-benchmark') && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    # The comment-on-pr workflow needs the issue number of the PR to be able to
    # comment so we output that to a file and pass it over as an artifact.

    runs-on: ubuntu-20.04
    steps:
      - name: Write PR number to file
        if: ${{ github.event_name == 'pull_request' }}
        run: echo -n ${{ github.event.number }} > pr_number.txt

      - name: Write empty file for PR number
        if: ${{ github.event_name != 'pull_request' }}
        run: echo -n > pr_number.txt

      - name: Upload results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr_number.txt
