name: performance-book

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

jobs:
  perf-book-pr:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'build-perf-book') && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: linux-pr
    runs-on: ubuntu-20.04
    env:
      CONDA_ENV_FILE: conda/dev_env.yml

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ${{env.CONDA_ENV_FILE}}

      - name: Install sasktran2
        shell: bash -l {0}
        run: |
          pip install .

      - name: Build Book
        shell: bash -l {0}
        id: benchmark
        run: |
          cd docs/performance_book
          make html

      - uses: actions/upload-artifact@v4
        with:
          name: performance_book
          path: docs/performance_book/build/html

  perf-book-main:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'build-perf-book') && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: linux-main
    runs-on: ubuntu-20.04
    env:
      CONDA_ENV_FILE: conda/dev_env.yml

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ${{env.CONDA_ENV_FILE}}

      - name: Install sasktran2
        shell: bash -l {0}
        run: |
          pip install .

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ''

      - name: Build Book
        shell: bash -l {0}
        id: benchmark
        run: |
          cd docs/performance_book
          make html

      - uses: actions/upload-artifact@v4
        with:
          name: performance_book_main
          path: docs/performance_book/build/html
