name: 'rattler-build'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64
    steps:
        - uses: actions/checkout@v4
        - name: Build conda package
          uses: prefix-dev/rattler-build-action@v0.2.33
          with:
            recipe-path: ci/rattler/recipe.yaml
            build-args: -c conda-forge/label/rust_dev -c conda-forge -m ci/rattler/variants/win_64_python3.10.____cpython.yaml
