name: 'rattler-build'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types:
      - published
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            target: x86_64
          - runner: ubuntu-24.04-arm
            target: aarch64
          - runner: macos-13
            target: x86_64
          - runner: macos-14
            target: aarch64
          - runner: windows-latest
            target: x86_64
    steps:
        - uses: actions/checkout@v4
        - name: Build conda package
          uses: prefix-dev/rattler-build-action@v0.2.33
          with:
            build-args: -r ci/rattler
