name: 'stubgen'

on:
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  update-stubs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Setup mamba build environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda/dev_env.yml

      - name: build
        shell: bash -el {0}
        run: |
          pip install -e .

      - name: stubgen
        shell: bash -el {0}
        run: |
          pip install pybind11-stubgen
          pybind11-stubgen sasktran2 -o src --root-suffix=-stubs

      - name: commit stubs
        run: |
          git add src/sasktran2-stubs
          git commit -m "Update typing stubs"
          git push
